name: Lint Dockerfile
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: [main]
    paths: [Dockerfile, .github/workflows/lint-dockerfiles.yml]
  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v5

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
