name: Lint Dockerfile

on:
  pull_request:
    branches: ['main']
    paths: ['Dockerfile', '.github/workflows/lint-dockerfiles.yml']
  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "Dockerfile"
