name: Lint GitHub Actions Workflows
permissions:
  contents: read
  pull-requests: write

on: 
  pull_request:
    branches: [main]
    paths: [.github/workflows/**]
  workflow_dispatch:

jobs:
  lint-workflows:
    # See: https://github.com/rhysd/actionlint/blob/main/docs/usage.md
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5
      - uses: docker://rhysd/actionlint:latest
        with:
          args: -color
    