name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    container:
      # Alternative to installing python, use a supported base os.
      # Simple verification of image that could be used for private runners
      image: 'jexmse/python-tox:3.12.8-slim-bookworm'

    steps:
      - uses: actions/checkout@v4
      - run: tox -e format

  lint:
    runs-on: ubuntu-latest
    container:
      image: 'jexmse/python-tox:3.12.8-slim-bookworm'

    steps:
      - uses: actions/checkout@v4
      - run: tox -e lint

  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Cache tox
        uses: actions/cache@v4
        with:
          path: '.tox'
          key: typecheck-3.12-${{ hashFiles('pyproject.toml', 'tox.ini') }}
          restore-keys: |
            typecheck-3.12-
      - run: pip install tox
      - run: tox -e typecheck

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
      - name: Cache tox
        uses: actions/cache@v4
        with:
          path: '.tox'
          key: test-${{ matrix.python }}-${{ hashFiles('pyproject.toml', 'tox.ini') }}
          restore-keys: |
            test-${{ matrix.python }}-
      - run: pip install tox
      - run: tox -e py
